/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.conexionSQL;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.ImageObserver;
import java.awt.image.ImageProducer;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Locale;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import modelo.Producto;
import javax.swing.JOptionPane;
import org.jfree.chart.*;
import org.jfree.chart.renderer.xy.XYSplineRenderer;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.axis.*;
import org.jfree.data.xy.*;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;


/**
 *
 * @author Casa
 */
public class GestionReportes extends javax.swing.JFrame {

    ArrayList<Producto> productos = new ArrayList<Producto>();
    
    public GestionReportes() {
        initComponents();
        this.setLocationRelativeTo(null);
        lineas.setVisible(false); barras.setVisible(false); pastel.setVisible(false);
        llenarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        radioPastel = new javax.swing.JRadioButton();
        radioLineas = new javax.swing.JRadioButton();
        radioBarras = new javax.swing.JRadioButton();
        capas = new javax.swing.JLayeredPane();
        lineas = new javax.swing.JPanel();
        barras = new javax.swing.JPanel();
        pastel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrincipal.setOpaque(false);
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Generar Reportes");
        panelPrincipal.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 14, 260, 50));

        radioPastel.setText("pastel");
        panelPrincipal.add(radioPastel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        radioLineas.setText("Lineas");
        radioLineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLineasActionPerformed(evt);
            }
        });
        panelPrincipal.add(radioLineas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        radioBarras.setText("barras");
        panelPrincipal.add(radioBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        lineas.setOpaque(false);
        capas.add(lineas);
        lineas.setBounds(0, 0, 790, 440);

        barras.setOpaque(false);
        capas.add(barras);
        barras.setBounds(0, 0, 790, 440);

        pastel.setOpaque(false);
        capas.add(pastel);
        pastel.setBounds(0, 0, 790, 440);

        panelPrincipal.add(capas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 790, 440));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 570));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Botones/botonRegresar.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 540, 40, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 210, 30));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondos/fondo_1.jpg"))); // NOI18N
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PrincipalAdministracion obj = new PrincipalAdministracion(); obj.setVisible(true); this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (radioLineas.isSelected()){
            lineas.setVisible(true); 
            capas.setLayer(lineas, 0,0);
             graficar();
        }else{
        }if(radioBarras.isSelected()){
            barras.setVisible(true); 
            capas.setLayer(barras, 0,0);
             graficar();
        }else{if(radioPastel.isSelected()){
            pastel.setVisible(true); 
            capas.setLayer(pastel, 0,0);
             graficar();
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void radioLineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLineasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioLineasActionPerformed

    private void graficar(){
        ChartPanel panel;
        JFreeChart chart = null;
        if (productos!=null){
        if (radioLineas.isSelected()){
            //Grafico de lineas
            int validar=1;
            XYSplineRenderer renderer = new XYSplineRenderer();
            XYSeriesCollection dataset = new XYSeriesCollection();
            
            ValueAxis x = new NumberAxis();
            ValueAxis y = new NumberAxis();
            
            XYSeries serie = new XYSeries("Datos"); 
            
            XYPlot plot;
            lineas.removeAll();
            int maximo=0;
            
                if (productos.size()<5){
                    maximo=productos.size();
                }else{}
                    maximo=5;
                try{
                    for (int fila=0;fila<maximo;fila++){
                        serie.add(Float.parseFloat(String.valueOf(fila)),
                                 Float.parseFloat(productos.get(fila).getCantidad()));
                    }
                }catch (Exception ex){
                    validar=0;
                }
                
                if (validar==1){
                    dataset.addSeries(serie);
                    
                    x.setLabel("Eje X");
                    y.setLabel("Eje Y");
                    plot = new XYPlot(dataset,x,y,renderer);
                    chart = new JFreeChart(plot);
                    chart.setTitle("Grafico de lineas");
                }else{JOptionPane.showMessageDialog(this, "Debe llenar la tabla con datos numericos");}
            
            }else{
                if (radioBarras.isSelected()){
                    //Grafico de barras
                    DefaultCategoryDataset data = new DefaultCategoryDataset();
                    
                    String producto1 = "Juan";
                    String producto2 = "Pedro";
                    String producto3 = "ismael";
                    String producto4 = "Roberto";
                    String producto5 = "Maria";
                    String dia1="20";
                    String dia2="Dia 2";
                    String dia3="Dia 3";
                    String dia4="Dia 4";
                    
                    data.addValue(30, producto1, producto1);
                    data.addValue(50, producto2, producto2);
                    data.addValue(20, producto3, producto3);
                    data.addValue(18, producto4, producto4);
                    data.addValue(7, producto5, producto5);
                    
                    chart = ChartFactory.createBarChart("Gráfico de barras", "Empleado", "cantidad de ventas",
                                                        data, PlotOrientation.VERTICAL,
                                                        true, true, true);
                    CategoryPlot plot2 = (CategoryPlot) chart.getPlot();
                    plot2.setCrosshairDatasetIndex(50);
                    plot2.setDomainGridlinesVisible(true);
                }else{
                }if (radioPastel.isSelected()){
                    //Grafico de pastel
                    
                    DefaultPieDataset data3 = new DefaultPieDataset();
                    data3.setValue("Categoria 1", 20);
                    data3.setValue("categoria 3", 60);
                    data3.setValue("categoria 3", 20);
                    
                    chart = ChartFactory.createPieChart3D("Grafico de pastel", data3, true, true, true);
                    
                    
                }
            }
        }
        
        panel = new ChartPanel (chart);
        panel.setBounds(0,0,500,300);
        if (radioLineas.isSelected()){
            lineas.add(panel);
            
            lineas.repaint();
        }else{
            if(radioBarras.isSelected()){
                barras.add(panel);
                barras.repaint();
            }else{
                pastel.add(panel);
                pastel.repaint();
            }
        }
    }
    
    private void llenarLista(){
        productos= conexionSQL.listaProductos(true);
        Collections.sort(productos, new Comparator(){
            @Override
            public int compare(Object o1, Object o2) {
                Producto obj = (Producto) o1; Producto obj2 = (Producto) o2;
                return new Integer(obj.getCantidad()).compareTo(new Integer(obj2.getCantidad()));
            }
        });
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barras;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLayeredPane capas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel lineas;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel pastel;
    private javax.swing.JRadioButton radioBarras;
    private javax.swing.JRadioButton radioLineas;
    private javax.swing.JRadioButton radioPastel;
    // End of variables declaration//GEN-END:variables
}
